import { Footer, Navbar } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "medad",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
