import type { Metadata } from "next";
import { Zain } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Navbar } from "@/components";

const zain = Zain({
  weight: ["200", "300", "400", "700"],
  subsets: ["arabic", "latin"],
});

export const metadata: Metadata = {
  title: "Medad",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"}>
      <NextIntlClientProvider messages={messages}>
        <body className={`${zain.className} antialiased`}>
         
          <main>{children}</main>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
